// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fgee_gram_axis_sums
NumericMatrix fgee_gram_axis_sums(const NumericMatrix& Q, int n_fun, int n_long, bool by_fn);
RcppExport SEXP _fastFGEE_fgee_gram_axis_sums(SEXP QSEXP, SEXP n_funSEXP, SEXP n_longSEXP, SEXP by_fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type n_fun(n_funSEXP);
    Rcpp::traits::input_parameter< int >::type n_long(n_longSEXP);
    Rcpp::traits::input_parameter< bool >::type by_fn(by_fnSEXP);
    rcpp_result_gen = Rcpp::wrap(fgee_gram_axis_sums(Q, n_fun, n_long, by_fn));
    return rcpp_result_gen;
END_RCPP
}
// fgee_kron_inverse_kernel
NumericMatrix fgee_kron_inverse_kernel(const NumericMatrix& Q, int n_fun, int n_long, int code_fn, double rho_fn, int code_long, double rho_long);
RcppExport SEXP _fastFGEE_fgee_kron_inverse_kernel(SEXP QSEXP, SEXP n_funSEXP, SEXP n_longSEXP, SEXP code_fnSEXP, SEXP rho_fnSEXP, SEXP code_longSEXP, SEXP rho_longSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< int >::type n_fun(n_funSEXP);
    Rcpp::traits::input_parameter< int >::type n_long(n_longSEXP);
    Rcpp::traits::input_parameter< int >::type code_fn(code_fnSEXP);
    Rcpp::traits::input_parameter< double >::type rho_fn(rho_fnSEXP);
    Rcpp::traits::input_parameter< int >::type code_long(code_longSEXP);
    Rcpp::traits::input_parameter< double >::type rho_long(rho_longSEXP);
    rcpp_result_gen = Rcpp::wrap(fgee_kron_inverse_kernel(Q, n_fun, n_long, code_fn, rho_fn, code_long, rho_long));
    return rcpp_result_gen;
END_RCPP
}
// fastk_fold_kernel
List fastk_fold_kernel(const NumericMatrix& X, const NumericVector& y, const NumericVector& w, const IntegerVector& fold_start, const IntegerVector& fold_end, const NumericMatrix& B, int family, double clip_prob, bool need_gradient);
RcppExport SEXP _fastFGEE_fastk_fold_kernel(SEXP XSEXP, SEXP ySEXP, SEXP wSEXP, SEXP fold_startSEXP, SEXP fold_endSEXP, SEXP BSEXP, SEXP familySEXP, SEXP clip_probSEXP, SEXP need_gradientSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type fold_start(fold_startSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type fold_end(fold_endSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type family(familySEXP);
    Rcpp::traits::input_parameter< double >::type clip_prob(clip_probSEXP);
    Rcpp::traits::input_parameter< bool >::type need_gradient(need_gradientSEXP);
    rcpp_result_gen = Rcpp::wrap(fastk_fold_kernel(X, y, w, fold_start, fold_end, B, family, clip_prob, need_gradient));
    return rcpp_result_gen;
END_RCPP
}
// fgee_sympd_inverse_cpp
NumericMatrix fgee_sympd_inverse_cpp(const NumericMatrix& x);
RcppExport SEXP _fastFGEE_fgee_sympd_inverse_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fgee_sympd_inverse_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// fgee_sympd_solve_cpp
NumericMatrix fgee_sympd_solve_cpp(const NumericMatrix& x, const NumericMatrix& b);
RcppExport SEXP _fastFGEE_fgee_sympd_solve_cpp(SEXP xSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fgee_sympd_solve_cpp(x, b));
    return rcpp_result_gen;
END_RCPP
}
// fgee_iar1_precision_bands_cpp
List fgee_iar1_precision_bands_cpp(const NumericVector& time, const double rho);
RcppExport SEXP _fastFGEE_fgee_iar1_precision_bands_cpp(SEXP timeSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(fgee_iar1_precision_bands_cpp(time, rho));
    return rcpp_result_gen;
END_RCPP
}
// fgee_iar1_precision_cpp
NumericMatrix fgee_iar1_precision_cpp(const NumericVector& time, const double rho);
RcppExport SEXP _fastFGEE_fgee_iar1_precision_cpp(SEXP timeSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(fgee_iar1_precision_cpp(time, rho));
    return rcpp_result_gen;
END_RCPP
}
// fgee_iar1_apply_precision_cpp
NumericMatrix fgee_iar1_apply_precision_cpp(const NumericMatrix& rhs, const NumericVector& time, const double rho);
RcppExport SEXP _fastFGEE_fgee_iar1_apply_precision_cpp(SEXP rhsSEXP, SEXP timeSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(fgee_iar1_apply_precision_cpp(rhs, time, rho));
    return rcpp_result_gen;
END_RCPP
}
// fgee_iar1_profile_nll_cpp
double fgee_iar1_profile_nll_cpp(const NumericVector& residual, const NumericVector& time, const double rho);
RcppExport SEXP _fastFGEE_fgee_iar1_profile_nll_cpp(SEXP residualSEXP, SEXP timeSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type residual(residualSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(fgee_iar1_profile_nll_cpp(residual, time, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastFGEE_fgee_gram_axis_sums", (DL_FUNC) &_fastFGEE_fgee_gram_axis_sums, 4},
    {"_fastFGEE_fgee_kron_inverse_kernel", (DL_FUNC) &_fastFGEE_fgee_kron_inverse_kernel, 7},
    {"_fastFGEE_fastk_fold_kernel", (DL_FUNC) &_fastFGEE_fastk_fold_kernel, 9},
    {"_fastFGEE_fgee_sympd_inverse_cpp", (DL_FUNC) &_fastFGEE_fgee_sympd_inverse_cpp, 1},
    {"_fastFGEE_fgee_sympd_solve_cpp", (DL_FUNC) &_fastFGEE_fgee_sympd_solve_cpp, 2},
    {"_fastFGEE_fgee_iar1_precision_bands_cpp", (DL_FUNC) &_fastFGEE_fgee_iar1_precision_bands_cpp, 2},
    {"_fastFGEE_fgee_iar1_precision_cpp", (DL_FUNC) &_fastFGEE_fgee_iar1_precision_cpp, 2},
    {"_fastFGEE_fgee_iar1_apply_precision_cpp", (DL_FUNC) &_fastFGEE_fgee_iar1_apply_precision_cpp, 3},
    {"_fastFGEE_fgee_iar1_profile_nll_cpp", (DL_FUNC) &_fastFGEE_fgee_iar1_profile_nll_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastFGEE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
