# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fgee_kron_inverse_kernel <- function(Q, n_fun, n_long, code_fn, rho_fn, code_long, rho_long) {
    .Call(`_fastFGEE_fgee_kron_inverse_kernel`, Q, n_fun, n_long, code_fn, rho_fn, code_long, rho_long)
}

.fastk_fold_kernel <- function(X, y, w, fold_start, fold_end, B, family, clip_prob, need_gradient) {
    .Call(`_fastFGEE_fastk_fold_kernel`, X, y, w, fold_start, fold_end, B, family, clip_prob, need_gradient)
}

fgee_sympd_inverse_cpp <- function(x) {
    .Call(`_fastFGEE_fgee_sympd_inverse_cpp`, x)
}

fgee_sympd_solve_cpp <- function(x, b) {
    .Call(`_fastFGEE_fgee_sympd_solve_cpp`, x, b)
}

fgee_iar1_precision_bands_cpp <- function(time, rho) {
    .Call(`_fastFGEE_fgee_iar1_precision_bands_cpp`, time, rho)
}

fgee_iar1_precision_cpp <- function(time, rho) {
    .Call(`_fastFGEE_fgee_iar1_precision_cpp`, time, rho)
}

fgee_iar1_apply_precision_cpp <- function(rhs, time, rho) {
    .Call(`_fastFGEE_fgee_iar1_apply_precision_cpp`, rhs, time, rho)
}

fgee_iar1_profile_nll_cpp <- function(residual, time, rho) {
    .Call(`_fastFGEE_fgee_iar1_profile_nll_cpp`, residual, time, rho)
}

